from django.contrib import admin
from django.urls import include, path

from .views import (
    baked_images,
    bake_index,
    bake_node,
    bake_recipe,
    base_images,
    build_log,
    cluster_create,
    cluster_delete,
    cluster_detail,
    cluster_edit,
    clusters,
    devices,
    doc_page,
    docs_index,
    download_base_image,
    drop_base_image,
    home,
    node_clone,
    node_create,
    node_delete,
    node_detail,
    node_edit,
    nodes,
    provisioners,
    sync_base_image,
)

urlpatterns = [
    path("", home, name="home"),
    path("devices/", devices, name="devices"),
    path("images/", base_images, name="base_images"),
    path("baked/", baked_images, name="baked_images"),
    path("baked/<uuid:build_id>/log/", build_log, name="build_log"),
    path("clusters/", clusters, name="clusters"),
    path("clusters/new/", cluster_create, name="cluster_create"),
    path("clusters/<slug:slug>/", cluster_detail, name="cluster_detail"),
    path("clusters/<slug:slug>/edit/", cluster_edit, name="cluster_edit"),
    path("clusters/<slug:slug>/delete/", cluster_delete, name="cluster_delete"),
    path("nodes/", nodes, name="nodes"),
    path("nodes/new/", node_create, name="node_create"),
    path("nodes/<int:pk>/", node_detail, name="node_detail"),
    path("nodes/<int:pk>/bake/", bake_node, name="bake_node"),
    path("nodes/<int:pk>/edit/", node_edit, name="node_edit"),
    path("nodes/<int:pk>/delete/", node_delete, name="node_delete"),
    path("nodes/<int:pk>/clone/", node_clone, name="node_clone"),
    path("provisioners/", provisioners, name="provisioners"),
    path("images/<int:pk>/download/", download_base_image, name="download_base_image"),
    path("images/<int:pk>/sync/", sync_base_image, name="sync_base_image"),
    path("images/<int:pk>/drop/", drop_base_image, name="drop_base_image"),
    path("bake/", bake_index, name="bake_index"),
    path("bake/<slug:slug>/", bake_recipe, name="bake_recipe"),
    path("docs/", docs_index, name="docs_index"),
    path("docs/<slug:slug>/", doc_page, name="doc_page"),
    path("admin/", admin.site.urls),
    path("api/catalog/", include("catalog.urls")),
    path("api/recipes/", include("recipes.urls")),
    path("api/builds/", include("builds.urls")),
    path("d/", include("builds.download_urls")),
]
