# Generated by Django 5.2.14 on 2026-05-21 21:09

import builds.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_values', models.JSONField(blank=True, default=dict, help_text='Filled-in RecipeOption values. Validated against the recipe at submit.')),
                ('label', models.CharField(blank=True, help_text='Optional user-supplied label (e.g. hostname or customer name).', max_length=120)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing'), ('building', 'Building'), ('finalizing', 'Finalizing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='queued', max_length=16)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('hardware_target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='build_requests', to='catalog.hardwaretarget')),
                ('recipe_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='build_requests', to='recipes.recipeversion')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='build_requests', to=settings.AUTH_USER_MODEL)),
                ('upstream_image', models.ForeignKey(help_text='Resolved base image (one upstream image per release+target).', on_delete=django.db.models.deletion.PROTECT, related_name='build_requests', to='catalog.upstreamimage')),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=8)),
                ('phase', models.CharField(blank=True, help_text="e.g. 'mount', 'salt', 'pack'", max_length=40)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='builds.buildrequest')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(help_text='Path within the artifacts storage backend (local FS or S3 key).', max_length=512)),
                ('filename', models.CharField(max_length=200)),
                ('format', models.CharField(choices=[('img.xz', 'img.xz'), ('img.gz', 'img.gz'), ('img.zip', 'img.zip'), ('img', 'img (raw)'), ('iso', 'iso')], default='img.xz', max_length=12)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('media_type', models.CharField(default='application/octet-stream', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('build', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='builds.buildrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=builds.models._generate_download_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited within TTL.')),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='builds.artifact')),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='buildrequest',
            index=models.Index(fields=['status', 'queued_at'], name='builds_buil_status_ee5bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='buildevent',
            index=models.Index(fields=['build', 'at'], name='builds_buil_build_i_527214_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadtoken',
            index=models.Index(fields=['expires_at'], name='builds_down_expires_a28135_idx'),
        ),
    ]
