# Generated by Django 5.2.14 on 2026-05-22 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildrequest',
            name='cluster',
            field=models.ForeignKey(blank=True, help_text='Optional Cluster the new device joins. Its `parameters` JSON merges into the pillar at bake time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_requests', to='tenants.cluster'),
        ),
        migrations.AddField(
            model_name='buildrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='build_requests', to='tenants.tenant'),
        ),
    ]
