# Generated by Django 5.2.14 on 2026-05-26 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_buildrequest_effective_model'),
        ('tenants', '0004_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildrequest',
            name='node',
            field=models.ForeignKey(blank=True, help_text="Optional Node this build bakes. When set, the node's parameters merge into the effective model (winning over the cluster) and the build inherits the node's cluster + hardware target.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_requests', to='tenants.node'),
        ),
    ]
