# Generated by Django 5.2.14 on 2026-05-22 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(blank=True, help_text="Users who can view + bake against this tenant's recipes.", related_name='tenants', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='Unique within the tenant — e.g. `prg-kube`, `home-iot`.', max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('kubernetes', 'Kubernetes'), ('docker_swarm', 'Docker Swarm'), ('salt_fleet', 'Salt Fleet'), ('home_assistant', 'Home Assistant'), ('batocera_lan', 'Batocera LAN'), ('esphome_network', 'ESPHome network'), ('robotics_swarm', 'Robotics / autopilot swarm'), ('generic', 'Generic')], default='generic', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text="Shared pillar tree merged into every bake that joins this cluster. Mirrors the recipe's `pillar_overrides` shape — keys like `kubernetes.api_endpoint`, `salt.master`, `mqtt.broker`.")),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_cluster_per_tenant')],
            },
        ),
    ]
