# Generated by Django 5.2.14 on 2026-05-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='kind',
            field=models.CharField(choices=[('kubernetes', 'Kubernetes'), ('docker_swarm', 'Docker Swarm'), ('salt_fleet', 'Salt Fleet'), ('home_assistant', 'Home Assistant'), ('batocera_lan', 'Batocera LAN'), ('esphome_network', 'ESPHome network'), ('robotics_swarm', 'Robotics / autopilot swarm'), ('vpn_mesh', 'VPN mesh (ZeroTier / WireGuard / Tailscale)'), ('generic', 'Generic')], default='generic', max_length=20),
        ),
    ]
