# Generated by Django 5.2.14 on 2026-05-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_cluster_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Free-form labels for filtering/grouping, e.g. ['prod', 'prg']."),
        ),
    ]
