# Generated by Django 5.2.14 on 2026-05-26 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_workflowstep'),
        ('recipes', '0003_recipe_provisioner'),
        ('tenants', '0003_cluster_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='Unique within the cluster — e.g. `cabinet-01`, `kube-master`.', max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('hostname', models.CharField(blank=True, help_text='Hostname / salt minion id baked in. Defaults to the slug.', max_length=120)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text="Node-specific pillar overrides — the most specific layer, winning over the cluster's shared parameters.")),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cluster', models.ForeignKey(help_text='The cluster this node joins; its parameters merge in.', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='tenants.cluster')),
                ('hardware_target', models.ForeignKey(help_text='The hardware we bake the image for.', on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='catalog.hardwaretarget')),
                ('preset', models.ForeignKey(help_text='The preset (recipe / role) this node implements.', on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='recipes.recipe')),
                ('upstream_image', models.ForeignKey(blank=True, help_text="Optional pinned base image; otherwise resolved from the preset's release + this node's hardware target at bake time.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='catalog.upstreamimage')),
            ],
            options={
                'ordering': ['cluster__tenant__name', 'cluster__slug', 'slug'],
                'constraints': [models.UniqueConstraint(fields=('cluster', 'slug'), name='uniq_node_per_cluster')],
            },
        ),
    ]
