# Generated by Django 5.2.14 on 2026-05-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='kind',
        ),
    ]
