# Generated by Django 5.2.14 on 2026-05-29 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_remove_cluster_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('zerotier', 'ZeroTier controller / Central')], max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(help_text='API base URL — ZeroTier Central (https://my.zerotier.com) or a self-hosted controller (https://<host>:9993).')),
                ('token', models.CharField(blank=True, help_text='API token used to authorize calls. Sensitive.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Owning tenant; leave blank for a shared/global integration.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'type', 'name'), name='uniq_integration_tenant_type_name')],
            },
        ),
        migrations.CreateModel(
            name='ZerotierIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network_id', models.CharField(help_text='16-hex ZeroTier network id this identity joins.', max_length=24)),
                ('member_id', models.CharField(blank=True, help_text='10-hex node/member address (identity.public prefix). Emitted to pillar as zerotier.networks[].id.', max_length=16)),
                ('public_key', models.TextField(blank=True, help_text='identity.public contents (zerotier-idtool getpublic).')),
                ('secret_key', models.TextField(blank=True, help_text='identity.secret contents (zerotier-idtool generate). Sensitive.')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zerotier_identities', to='tenants.node')),
            ],
            options={
                'verbose_name': 'ZeroTier identity',
                'verbose_name_plural': 'ZeroTier identities',
                'ordering': ['node', 'network_id'],
                'constraints': [models.UniqueConstraint(fields=('node', 'network_id'), name='uniq_zt_identity_node_network')],
            },
        ),
    ]
