# Generated by Django 5.2.14 on 2026-05-31 22:18

import osbakery.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_integration_zerotieridentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='token',
            field=osbakery.fields.EncryptedTextField(blank=True, help_text='API token used to authorize calls. Encrypted at rest.'),
        ),
    ]
