# Generated by Django 5.2.14 on 2026-06-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_wireguardidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='type',
            field=models.CharField(choices=[('zerotier', 'ZeroTier controller / Central'), ('wg_easy', 'wg-easy WireGuard controller')], max_length=32),
        ),
    ]
