# Generated by Django 5.2.14 on 2026-05-21 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='e.g. arm64, armv7l, amd64, i686', unique=True)),
                ('name', models.CharField(help_text="Human label, e.g. 'ARM 64-bit (aarch64)'", max_length=80)),
                ('family', models.CharField(choices=[('arm', 'ARM'), ('x86', 'x86'), ('riscv', 'RISC-V'), ('other', 'Other')], default='other', max_length=16)),
                ('bits', models.PositiveSmallIntegerField(default=64)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['family', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='e.g. batocera, raspios, ubuntu', unique=True)),
                ('name', models.CharField(max_length=120)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(choices=[('retro', 'Retro gaming'), ('desktop', 'Desktop'), ('server', 'Server'), ('embedded', 'Embedded'), ('iot', 'IoT')], default='server', max_length=16)),
                ('homepage', models.URLField(blank=True)),
                ('license', models.CharField(blank=True, max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HardwareTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='e.g. rpi5, rpi4, rpi-zero2w, pc-x86_64-uefi', unique=True)),
                ('name', models.CharField(max_length=120)),
                ('boot_method', models.CharField(choices=[('rpi', 'Raspberry Pi firmware'), ('uboot', 'U-Boot'), ('uefi', 'UEFI'), ('bios', 'Legacy BIOS'), ('custom', 'Custom')], max_length=16)),
                ('soc', models.CharField(blank=True, help_text='System-on-chip, e.g. BCM2712', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hardware_targets', to='catalog.architecture')),
            ],
            options={
                'ordering': ['architecture__slug', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='OSRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(help_text='e.g. 41, 24.04.1, 2025-05-13', max_length=40)),
                ('codename', models.CharField(blank=True, help_text='e.g. Bookworm, Noble', max_length=80)),
                ('channel', models.CharField(choices=[('stable', 'Stable'), ('lts', 'LTS'), ('beta', 'Beta'), ('dev', 'Development'), ('nightly', 'Nightly')], default='stable', max_length=16)),
                ('released_on', models.DateField(blank=True, null=True)),
                ('end_of_life_on', models.DateField(blank=True, null=True)),
                ('release_notes_url', models.URLField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text="If true, recipes that don't pin a release will resolve to this one.")),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='catalog.operatingsystem')),
            ],
            options={
                'ordering': ['operating_system__slug', '-released_on', '-version'],
            },
        ),
        migrations.CreateModel(
            name='UpstreamImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.CharField(blank=True, help_text="Vendor variant, e.g. 'lite', 'desktop-full', 'server-minimal'.", max_length=60)),
                ('format', models.CharField(choices=[('img.xz', 'img.xz'), ('img.gz', 'img.gz'), ('img.zip', 'img.zip'), ('img', 'img (raw)'), ('iso', 'iso'), ('qcow2', 'qcow2')], default='img.xz', max_length=12)),
                ('source_url', models.URLField(help_text='Where the upstream image lives (https://...).')),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('local_path', models.CharField(blank=True, help_text='Path under PACKER cache once mirrored locally.', max_length=512)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('hardware_target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upstream_images', to='catalog.hardwaretarget')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.osrelease')),
            ],
            options={
                'ordering': ['release', 'hardware_target__slug', 'variant'],
            },
        ),
        migrations.AddConstraint(
            model_name='osrelease',
            constraint=models.UniqueConstraint(fields=('operating_system', 'version', 'channel'), name='uniq_release_per_os_version_channel'),
        ),
        migrations.AddConstraint(
            model_name='upstreamimage',
            constraint=models.UniqueConstraint(fields=('release', 'hardware_target', 'variant'), name='uniq_upstream_image_per_release_target_variant'),
        ),
    ]
