# Generated by Django 5.2.14 on 2026-05-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaretarget',
            name='image_url',
            field=models.URLField(blank=True, help_text='Product photo (Wikipedia Commons, vendor CDN, ...). Used on the /devices/ page; falls back to a letter avatar.'),
        ),
    ]
