# Generated by Django 5.2.14 on 2026-05-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_hardwaretarget_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamimage',
            name='cache_storage_key',
            field=models.CharField(blank=True, help_text='Object key inside the artifacts S3 bucket where the decompressed upstream image is mirrored. Filled in by `manage.py refresh_upstream`. Preferred over local_path.', max_length=512),
        ),
        migrations.AlterField(
            model_name='upstreamimage',
            name='local_path',
            field=models.CharField(blank=True, help_text='Filesystem path on the build host when a local mirror is in use. Legacy — prefer cache_storage_key (MinIO/S3).', max_length=512),
        ),
    ]
