# Generated by Django 5.2.14 on 2026-05-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_upstreamimage_cache_storage_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamimage',
            name='mirror_started_at',
            field=models.DateTimeField(blank=True, help_text="Set when a mirror (sync) job is queued/running; cleared on failure. While set and not yet cached, the UI shows 'syncing'.", null=True),
        ),
    ]
