# Generated by Django 5.2.14 on 2026-05-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_upstreamimage_mirror_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provisioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(choices=[('salt', 'Salt'), ('ansible', 'Ansible'), ('cloud-init', 'Cloud-Init')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('available_states', models.JSONField(blank=True, default=list, help_text="The units this provisioner can apply — Salt formulas/states (e.g. 'base.locale'), Ansible roles, or cloud-init modules. Each item: {slug, name, description}.")),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
