# Generated by Django 5.2.14 on 2026-05-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_provisioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsystem',
            name='changelog_url',
            field=models.URLField(blank=True, help_text='Upstream changelog / release-notes page, linked from images.'),
        ),
    ]
