# Generated by Django 5.2.14 on 2026-05-25 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_operatingsystem_changelog_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.SlugField(help_text='e.g. fetch-base, provision, pack, push-s3', max_length=40)),
                ('image', models.CharField(help_text='Container image the step runs, e.g. ghcr.io/cznewt/os-bakery-step-pack:latest', max_length=200)),
                ('command', models.JSONField(blank=True, default=list, help_text='Optional command/args override (list of strings).')),
                ('env', models.JSONField(blank=True, default=dict, help_text='Extra env vars for this step (merged over the build-wide env).')),
                ('description', models.TextField(blank=True)),
                ('provisioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='catalog.provisioner')),
            ],
            options={
                'ordering': ['provisioner', 'order'],
                'constraints': [models.UniqueConstraint(fields=('provisioner', 'order'), name='uniq_step_order_per_provisioner')],
            },
        ),
    ]
