# Generated by Django 5.2.14 on 2026-05-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_workflowstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamimage',
            name='extra_targets',
            field=models.ManyToManyField(blank=True, help_text='Additional devices that run this exact same image (beyond the primary hardware_target) — e.g. the x86_64 build shared by Steam Deck + Loki Zero.', related_name='shared_images', to='catalog.hardwaretarget'),
        ),
    ]
