# Generated by Django 5.2.14 on 2026-06-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_rename_generic_arm64'),
    ]

    operations = [
        migrations.CreateModel(
            name='WireguardPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='e.g. gedu-prg, newt-prg.', unique=True)),
                ('name', models.CharField(max_length=120)),
                ('interface', models.CharField(default='wg0', help_text='Local WireGuard interface on the device; matches tenants.WireguardIdentity.interface and wireguard.interfaces[].name.', max_length=32)),
                ('endpoint_host', models.CharField(help_text='Public FQDN/IP clients dial (WAN side of the UDP forward), e.g. lab.geekedu.eu.', max_length=255)),
                ('endpoint_port', models.PositiveIntegerField(default=51820)),
                ('public_key', models.TextField(blank=True, help_text="Server's WireGuard public key (the [Peer] PublicKey clients use). Blank until the endpoint is up; read via `wg show`.")),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='Subnets routed through the tunnel, e.g. ["10.50.61.0/24", "10.13.13.0/24"] (split) or ["0.0.0.0/0"] (full).')),
                ('persistent_keepalive', models.PositiveIntegerField(default=25, help_text='Seconds; keeps NAT open from behind-NAT devices. 0 = off.')),
                ('dns', models.JSONField(blank=True, default=list, help_text='Optional DNS servers pushed for the tunnel.')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
