# Generated by Django 5.2.14 on 2026-06-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_wireguardpeer'),
        ('tenants', '0009_alter_integration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireguardpeer',
            name='controller',
            field=models.ForeignKey(blank=True, help_text='Optional wg-easy controller (Integration of type wg_easy). When set, attaching this peer to a node registers the node on the controller (mints its keypair + tunnel IP) instead of generating a key locally — the WireGuard analogue of ZeroTier registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wireguard_peers', to='tenants.integration'),
        ),
    ]
