# Generated by Django 5.2.14 on 2026-06-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_wireguardpeer_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireguardpeer',
            name='address_pool',
            field=models.CharField(blank=True, help_text='Overlay subnet to allocate node tunnel IPs from (CIDR), e.g. 10.13.13.0/24 — the node form pre-fills the next free address.', max_length=64),
        ),
    ]
