# Generated by Django 5.2.14 on 2026-06-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_wireguardpeer_address_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingsystem',
            name='kind',
            field=models.CharField(choices=[('retro', 'Retro gaming'), ('desktop', 'Desktop'), ('server', 'Server'), ('embedded', 'Embedded'), ('iot', 'IoT'), ('mobile', 'Mobile')], default='server', max_length=16),
        ),
    ]
