# Generated by Django 5.2.14 on 2026-05-21 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('summary', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True, help_text='Markdown supported.')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('internal', 'Internal'), ('public', 'Public')], default='private', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='draft', max_length=12)),
                ('icon', models.CharField(blank=True, help_text='UI icon hint.', max_length=80)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='catalog.operatingsystem')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_recipes', to=settings.AUTH_USER_MODEL)),
                ('pinned_release', models.ForeignKey(blank=True, help_text='If set, builds always use this release; otherwise the OS default is used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='catalog.osrelease')),
                ('supported_hardware', models.ManyToManyField(help_text='Hardware targets that this recipe is known to produce working images for.', related_name='recipes', to='catalog.hardwaretarget')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text="Pillar key (becomes pillar['options'][key] at build time).", max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('help_text', models.CharField(blank=True, max_length=240)),
                ('kind', models.CharField(choices=[('string', 'String'), ('text', 'Multiline text'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('choice', 'Single choice'), ('multi_choice', 'Multiple choice'), ('file', 'File upload'), ('ssh_key', 'SSH public key'), ('secret', 'Secret (stored encrypted)')], default='string', max_length=16)),
                ('default', models.JSONField(blank=True, null=True)),
                ('choices', models.JSONField(blank=True, default=list, help_text='For choice/multi_choice kinds: list of {value, label} dicts.')),
                ('required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='recipes.recipe')),
            ],
            options={
                'ordering': ['recipe__slug', 'sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('recipe', 'key'), name='uniq_option_per_recipe')],
            },
        ),
        migrations.CreateModel(
            name='RecipeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(help_text="Semver-ish, e.g. '1.4.0'.", max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('salt_top_yaml', models.TextField(blank=True, help_text='Optional inline `top.sls` fragment. If empty, `salt/top/{recipe.slug}.sls` is used.')),
                ('salt_states', models.JSONField(blank=True, default=list, help_text="Ordered list of Salt state IDs to apply, e.g. ['base.hardening', 'batocera.arcade'].")),
                ('pillar_overrides', models.JSONField(blank=True, default=dict, help_text='Pillar tree merged on top of the per-OS defaults at build time.')),
                ('changelog', models.TextField(blank=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='recipes.recipe')),
            ],
            options={
                'ordering': ['recipe__slug', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('recipe', 'version'), name='uniq_recipe_version')],
            },
        ),
    ]
