# Generated by Django 5.2.14 on 2026-05-22 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this recipe. Leave blank for global recipes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='tenants.tenant'),
        ),
    ]
