# Generated by Django 5.2.14 on 2026-05-25 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_provisioner'),
        ('recipes', '0002_recipe_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='provisioner',
            field=models.ForeignKey(blank=True, help_text='How this recipe customizes the image (Salt by default). Falls back to Salt when unset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='catalog.provisioner'),
        ),
    ]
