# Generated by Django 5.2.14 on 2026-05-21 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('relative_path', models.CharField(help_text="Path relative to PACKER_TEMPLATES_ROOT (e.g. 'batocera/rpi5/template.pkr.hcl').", max_length=240)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=12)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_log', models.TextField(blank=True)),
                ('hardware_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packer_templates', to='catalog.hardwaretarget')),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packer_templates', to='catalog.operatingsystem')),
                ('pinned_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packer_templates', to='catalog.osrelease')),
                ('produces', models.ManyToManyField(blank=True, help_text='UpstreamImage rows this template keeps fresh.', related_name='produced_by', to='catalog.upstreamimage')),
            ],
            options={
                'ordering': ['operating_system__slug', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='SaltFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('relative_path', models.CharField(help_text="Path relative to SALT_STATES_ROOT (e.g. 'batocera/arcade').", max_length=240)),
                ('description', models.TextField(blank=True)),
                ('requires', models.JSONField(blank=True, default=list, help_text='List of formula slugs this one depends on (informational).')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal helper formulas (not exposed to users in the recipe builder).')),
                ('operating_systems', models.ManyToManyField(blank=True, help_text='OSes this formula is known to work against.', related_name='salt_formulas', to='catalog.operatingsystem')),
                ('used_by', models.ManyToManyField(blank=True, related_name='formulas', to='recipes.recipe')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
